#!/usr/bin/env python3
"""Generate keymap.json (window-relative key coords) from inputs.json.

inputs.json (ilovecherries/sb-inputredirection) gives each key's position in the
bottom-screen pixel space (320x240). With the window pinned to 400pt wide, Azahar renders
the top screen 1:1 (400px->400pt) and the 320-wide bottom screen centered -> 40pt left
margin, below title bar (32) + top screen (240) = 272. So the transform is identity scale
with offset (40, 272): window = input + (40, 272).
"""
import json
import pathlib

HERE = pathlib.Path(__file__).parent
inp = json.load(open(HERE / "inputs.json"))
BX, BY = 40, 272  # bottom-screen origin in window points (scale 1.0)

special = {"space": ["SPACE", " "], "backspace": ["BACKSPACE"], "return": ["ENTER"]}
out = {
    "_note": f"GENERATED by gen_keymap.py from inputs.json. transform: window = input + ({BX},{BY}), "
             f"scale 1.0 (top screen 1:1, bottom 320 centered in 400 -> 40pt margin).",
    "_confirmed": ["1", "6", "RUN", "SHIFT", "BACKSPACE"],
}
for k, v in inp.items():
    coord = [v["x"] + BX, v["y"] + BY]
    for name in special.get(k, [k]):
        out[name] = coord
out["SHIFT"] = [58, 473]   # confirmed empirically (clear_line works); not in inputs.json
out["RUN"] = [328, 275]    # tab above the keyboard, confirmed empirically
out["DIRECT"] = [55, 498]
out["EDIT"] = [110, 498]
out["YES"] = [318, 488]   # Confirm-Write dialog, bottom-right (confirmed)
out["NO"] = [110, 488]    # Confirm-Write dialog, bottom-left (estimate)
json.dump(out, open(HERE / "keymap.json", "w"), indent=0)
nk = sum(1 for k in out if not k.startswith("_"))
print(f"wrote {nk} keys. samples: 1={out['1']} 6={out['6']} 7={out['7']} 0={out['0']} "
      f"Q={out['Q']} A={out['A']} $={out['$']} ENTER={out['ENTER']} BACKSPACE={out['BACKSPACE']}")
